services:
  bot: &bot
    build: .
    ports:
      - 3030:3030
      - 5555:5555
    volumes:
      - ./bot_sessions:/app/bot_sessions:rw
      - ./data/logs:/app/utils/logs:rw
      - /etc/localtime:/etc/localtime:ro  # Monta la zona horaria del host
      - /etc/timezone:/etc/timezone:ro    # Monta la configuración de zona horaria del host
    env_file: .env
    environment:
      - TZ=America/Panama
    cap_add: 
      - SYS_ADMIN
    restart: always
    networks:
      - chat_default
    command: ["pm2-runtime", "start", "./src/app.js", "--cron", "0 */12 * * *"]

volumes:
  bot_sessions:
  data:

networks:
  chat_default:
    external: true
