services:
  bot: &bot
    build: .
    ports:
      - 3030:3030
      - 5555:5555
    volumes:
      - ./bot_sessions:/app/bot_sessions:rw
      - ./logs:/app/src/utils/logs:rw
    env_file: .env
    environment:
      - TZ=America/Panama
    restart: always
    networks:
      - chat_default
    command: ["pm2-runtime", "start", "./src/app.js", "--cron", "0 */12 * * *"]

volumes:
  bot_sessions:
  logs:

networks:
  chat_default:
    external: true
